language: python
python: 2.7

virtualenv:
  system_site_packages: true

branches:
    only:
        - master

before_install:

# general setup
- sudo apt-get install python-pip

# test installation from last pypi release
pip install easytest



script:
- nosetests



