language: python
python: 2.7

virtualenv:
  system_site_packages: true

branches:
    only:
        - master

before_install:
    # general setup
    - sudo apt-get install python-pip
    - sudo apt-get install libhdf5-openmpi-dev libnetcdf-dev libopenmpi-dev

    - sudo apt-get install libgdal1h
    - sudo apt-get install libgdal-dev

    - sudo pip install netCDF4

    # test installation from last pypi release
    - pip install easytest
    - pip uninstall -y easytest



script:
- nosetests



