language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

virtualenv:
system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install libhdf5-openmpi-dev libnetcdf-dev libopenmpi-dev
  - sudo apt-get install libgdal1h
  - sudo apt-get install libgdal-dev

install:
  - pip install netcdf4
   
  # test installation from pip
  - pip install easytest
  - python -c "from easytest import *"
  - yes | pip uninstall easytest

# before_install:
#     # general setup
#     - sudo apt-get install python-pip
#     - sudo apt-get install libhdf5-openmpi-dev libnetcdf-dev libopenmpi-dev
# 
#     - sudo apt-get install libgdal1h
#     - sudo apt-get install libgdal-dev
# 
#     - sudo pip install netCDF4
# 
#     # test installation from last pypi release
#     - pip install easytest
#     - pip uninstall -y easytest

script:
 - nosetests



